--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5
-- Dumped by pg_dump version 13.2

-- Started on 2021-03-30 20:13:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

--
-- TOC entry 202 (class 1259 OID 24654)
-- Name: Coverings; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Coverings" (
    "PatientId" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Primary" boolean NOT NULL
);


ALTER TABLE public."Coverings" OWNER TO "EHRApp";

--
-- TOC entry 204 (class 1259 OID 24674)
-- Name: Medications; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Medications" (
    "Id" integer NOT NULL,
    "PatientId" uuid NOT NULL,
    "UserId" text,
    "Name" text,
    "Frequency" text,
    "Dosage" text,
    "Expires" timestamp without time zone,
    "PatientMRN" uuid
);


ALTER TABLE public."Medications" OWNER TO "EHRApp";

--
-- TOC entry 203 (class 1259 OID 24672)
-- Name: Medications_Id_seq; Type: SEQUENCE; Schema: public; Owner: EHRApp
--

ALTER TABLE public."Medications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Medications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 24699)
-- Name: Notes; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Notes" (
    "Id" integer NOT NULL,
    "PatientId" uuid NOT NULL,
    "UserId" text,
    "Text" text,
    "Recorded" timestamp without time zone NOT NULL,
    "PatientMRN" uuid
);


ALTER TABLE public."Notes" OWNER TO "EHRApp";

--
-- TOC entry 205 (class 1259 OID 24697)
-- Name: Notes_Id_seq; Type: SEQUENCE; Schema: public; Owner: EHRApp
--

ALTER TABLE public."Notes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 197 (class 1259 OID 24618)
-- Name: Patients; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Patients" (
    "MRN" uuid NOT NULL,
    "Name" text,
    "Gender" text,
    "Weight" numeric NOT NULL,
    "Height" numeric NOT NULL,
    "DOB" timestamp without time zone NOT NULL
);


ALTER TABLE public."Patients" OWNER TO "EHRApp";

--
-- TOC entry 198 (class 1259 OID 24626)
-- Name: Roles; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Roles" (
    "Id" text NOT NULL,
    "Name" text,
    "NormalizedName" text,
    "ConcurrencyStamp" text
);


ALTER TABLE public."Roles" OWNER TO "EHRApp";

--
-- TOC entry 208 (class 1259 OID 24724)
-- Name: Tests; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Tests" (
    "Id" integer NOT NULL,
    "TestTypeId" integer NOT NULL,
    "PatientId" uuid NOT NULL,
    "UserId" text,
    "Results" text,
    "Performed" timestamp without time zone,
    "PatientMRN" uuid
);


ALTER TABLE public."Tests" OWNER TO "EHRApp";

--
-- TOC entry 207 (class 1259 OID 24722)
-- Name: Tests_Id_seq; Type: SEQUENCE; Schema: public; Owner: EHRApp
--

ALTER TABLE public."Tests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 24636)
-- Name: TypesOfTests; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."TypesOfTests" (
    "Id" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."TypesOfTests" OWNER TO "EHRApp";

--
-- TOC entry 199 (class 1259 OID 24634)
-- Name: TypesOfTests_Id_seq; Type: SEQUENCE; Schema: public; Owner: EHRApp
--

ALTER TABLE public."TypesOfTests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TypesOfTests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 24641)
-- Name: Users; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."Users" (
    "Id" text NOT NULL,
    "RoleId" text,
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."Users" OWNER TO "EHRApp";

--
-- TOC entry 196 (class 1259 OID 16426)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: EHRApp
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "EHRApp";

--
-- TOC entry 2886 (class 0 OID 24654)
-- Dependencies: 202
-- Data for Name: Coverings; Type: TABLE DATA; Schema: public; Owner: EHRApp
--



--
-- TOC entry 2888 (class 0 OID 24674)
-- Dependencies: 204
-- Data for Name: Medications; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."Medications" ("Id", "PatientId", "UserId", "Name", "Frequency", "Dosage", "Expires", "PatientMRN") VALUES (1, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'Ativan', 'q4', '10ml', '2021-05-05 00:00:00', NULL);
INSERT INTO public."Medications" ("Id", "PatientId", "UserId", "Name", "Frequency", "Dosage", "Expires", "PatientMRN") VALUES (2, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'Epinephren', 'as needed', '10ml', '2021-05-05 00:00:00', NULL);
INSERT INTO public."Medications" ("Id", "PatientId", "UserId", "Name", "Frequency", "Dosage", "Expires", "PatientMRN") VALUES (3, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'Zofran', '1 daily', '10mg', '2021-10-24 00:00:00', NULL);


--
-- TOC entry 2890 (class 0 OID 24699)
-- Dependencies: 206
-- Data for Name: Notes; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."Notes" ("Id", "PatientId", "UserId", "Text", "Recorded", "PatientMRN") VALUES (1, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'test', '2021-03-28 11:16:54.411765', NULL);
INSERT INTO public."Notes" ("Id", "PatientId", "UserId", "Text", "Recorded", "PatientMRN") VALUES (2, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'tests', '2021-03-28 11:21:38.224058', NULL);
INSERT INTO public."Notes" ("Id", "PatientId", "UserId", "Text", "Recorded", "PatientMRN") VALUES (3, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'testing
', '2021-03-28 11:31:19.912309', NULL);
INSERT INTO public."Notes" ("Id", "PatientId", "UserId", "Text", "Recorded", "PatientMRN") VALUES (4, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'testing again
', '2021-03-28 13:53:07.516987', NULL);
INSERT INTO public."Notes" ("Id", "PatientId", "UserId", "Text", "Recorded", "PatientMRN") VALUES (5, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', 'whyyy
', '2021-03-28 14:11:06.257663', NULL);
INSERT INTO public."Notes" ("Id", "PatientId", "UserId", "Text", "Recorded", "PatientMRN") VALUES (6, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', '1 more
', '2021-03-28 14:13:53.946355', NULL);


--
-- TOC entry 2881 (class 0 OID 24618)
-- Dependencies: 197
-- Data for Name: Patients; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."Patients" ("MRN", "Name", "Gender", "Weight", "Height", "DOB") VALUES ('5fef4289-c898-46d3-a6f4-550d0ca2e7b1', 'Smitty', 'Male', 180, 6, '1990-10-24 00:00:00');
INSERT INTO public."Patients" ("MRN", "Name", "Gender", "Weight", "Height", "DOB") VALUES ('d6e374f3-3e87-406f-860d-ca9126135064', 'Andy', 'Male', 150, 5.2, '1995-10-24 00:00:00');


--
-- TOC entry 2882 (class 0 OID 24626)
-- Dependencies: 198
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES ('0', 'Initial', 'Initial', NULL);
INSERT INTO public."Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES ('1', 'Physician', 'Physician', NULL);
INSERT INTO public."Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES ('2', 'Nurse', 'Nurse', NULL);
INSERT INTO public."Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES ('3', 'Admin', 'Admin', NULL);


--
-- TOC entry 2892 (class 0 OID 24724)
-- Dependencies: 208
-- Data for Name: Tests; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."Tests" ("Id", "TestTypeId", "PatientId", "UserId", "Results", "Performed", "PatientMRN") VALUES (1, 1, '5fef4289-c898-46d3-a6f4-550d0ca2e7b1', '68fd044a-f172-4549-9b91-bfd31aa931e3', NULL, NULL, NULL);


--
-- TOC entry 2884 (class 0 OID 24636)
-- Dependencies: 200
-- Data for Name: TypesOfTests; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."TypesOfTests" ("Id", "Name") VALUES (1, 'MRI');
INSERT INTO public."TypesOfTests" ("Id", "Name") VALUES (2, 'CT Scan');
INSERT INTO public."TypesOfTests" ("Id", "Name") VALUES (3, 'CBC');


--
-- TOC entry 2885 (class 0 OID 24641)
-- Dependencies: 201
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."Users" ("Id", "RoleId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('fdf04144-896d-4e23-95c8-7b692a03cbbe', '2', 'Andrew', 'ANDREW', 'asmith1138@gmail.com', 'ASMITH1138@GMAIL.COM', false, 'AQAAAAEAACcQAAAAELEe2dnoMBjfvvB249ky6EGzfPkDz25o5qlVpDqW+zJs4vyPrmjtAeP755elxldY1g==', 'TCTX6MA766LRGSOGMMRUJ7667ZGI232V', '5344ef43-2efb-4c9c-8f36-f5c802aa7420', NULL, false, false, NULL, true, 0);
INSERT INTO public."Users" ("Id", "RoleId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES ('68fd044a-f172-4549-9b91-bfd31aa931e3', '1', 'Danielle', 'DANIELLE', 'asmith1138+danielle@gmail.com', 'ASMITH1138+DANIELLE@GMAIL.COM', false, 'AQAAAAEAACcQAAAAEMFyE7zQjYsjvpDso8pqS6GkY9yTqq2eHiPXfjY3PG/hbJSZsy8067dKdg+OfEO/+Q==', 'B7NHWXG3D75CSKHUAPXVBAKO73O2X4OJ', '70ada2ba-d061-4e5a-8271-d4fd2afc2c30', NULL, false, false, NULL, true, 0);


--
-- TOC entry 2880 (class 0 OID 16426)
-- Dependencies: 196
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: EHRApp
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20210318004853_UserUpdate', '5.0.4');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20210318020816_Initial', '5.0.4');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20210321161641_RoleUpdate', '5.0.4');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20210328185812_FixTestType', '5.0.4');


--
-- TOC entry 2898 (class 0 OID 0)
-- Dependencies: 203
-- Name: Medications_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: EHRApp
--

SELECT pg_catalog.setval('public."Medications_Id_seq"', 3, true);


--
-- TOC entry 2899 (class 0 OID 0)
-- Dependencies: 205
-- Name: Notes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: EHRApp
--

SELECT pg_catalog.setval('public."Notes_Id_seq"', 6, true);


--
-- TOC entry 2900 (class 0 OID 0)
-- Dependencies: 207
-- Name: Tests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: EHRApp
--

SELECT pg_catalog.setval('public."Tests_Id_seq"', 1, true);


--
-- TOC entry 2901 (class 0 OID 0)
-- Dependencies: 199
-- Name: TypesOfTests_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: EHRApp
--

SELECT pg_catalog.setval('public."TypesOfTests_Id_seq"', 1, false);


--
-- TOC entry 2729 (class 2606 OID 24661)
-- Name: Coverings PK_Coverings; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Coverings"
    ADD CONSTRAINT "PK_Coverings" PRIMARY KEY ("PatientId", "UserId");


--
-- TOC entry 2734 (class 2606 OID 24681)
-- Name: Medications PK_Medications; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Medications"
    ADD CONSTRAINT "PK_Medications" PRIMARY KEY ("Id");


--
-- TOC entry 2739 (class 2606 OID 24706)
-- Name: Notes PK_Notes; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Notes"
    ADD CONSTRAINT "PK_Notes" PRIMARY KEY ("Id");


--
-- TOC entry 2719 (class 2606 OID 24625)
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("MRN");


--
-- TOC entry 2721 (class 2606 OID 24633)
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- TOC entry 2745 (class 2606 OID 24731)
-- Name: Tests PK_Tests; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Tests"
    ADD CONSTRAINT "PK_Tests" PRIMARY KEY ("Id");


--
-- TOC entry 2723 (class 2606 OID 24640)
-- Name: TypesOfTests PK_TypesOfTests; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."TypesOfTests"
    ADD CONSTRAINT "PK_TypesOfTests" PRIMARY KEY ("Id");


--
-- TOC entry 2726 (class 2606 OID 24648)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 2717 (class 2606 OID 16430)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2727 (class 1259 OID 24752)
-- Name: IX_Coverings_UserId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Coverings_UserId" ON public."Coverings" USING btree ("UserId");


--
-- TOC entry 2730 (class 1259 OID 24753)
-- Name: IX_Medications_PatientId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Medications_PatientId" ON public."Medications" USING btree ("PatientId");


--
-- TOC entry 2731 (class 1259 OID 24754)
-- Name: IX_Medications_PatientMRN; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Medications_PatientMRN" ON public."Medications" USING btree ("PatientMRN");


--
-- TOC entry 2732 (class 1259 OID 24755)
-- Name: IX_Medications_UserId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Medications_UserId" ON public."Medications" USING btree ("UserId");


--
-- TOC entry 2735 (class 1259 OID 24756)
-- Name: IX_Notes_PatientId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Notes_PatientId" ON public."Notes" USING btree ("PatientId");


--
-- TOC entry 2736 (class 1259 OID 24757)
-- Name: IX_Notes_PatientMRN; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Notes_PatientMRN" ON public."Notes" USING btree ("PatientMRN");


--
-- TOC entry 2737 (class 1259 OID 24758)
-- Name: IX_Notes_UserId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Notes_UserId" ON public."Notes" USING btree ("UserId");


--
-- TOC entry 2740 (class 1259 OID 24759)
-- Name: IX_Tests_PatientId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Tests_PatientId" ON public."Tests" USING btree ("PatientId");


--
-- TOC entry 2741 (class 1259 OID 24760)
-- Name: IX_Tests_PatientMRN; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Tests_PatientMRN" ON public."Tests" USING btree ("PatientMRN");


--
-- TOC entry 2742 (class 1259 OID 24761)
-- Name: IX_Tests_TestTypeId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Tests_TestTypeId" ON public."Tests" USING btree ("TestTypeId");


--
-- TOC entry 2743 (class 1259 OID 24762)
-- Name: IX_Tests_UserId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Tests_UserId" ON public."Tests" USING btree ("UserId");


--
-- TOC entry 2724 (class 1259 OID 24772)
-- Name: IX_Users_RoleId; Type: INDEX; Schema: public; Owner: EHRApp
--

CREATE INDEX "IX_Users_RoleId" ON public."Users" USING btree ("RoleId");


--
-- TOC entry 2747 (class 2606 OID 24662)
-- Name: Coverings FK_Coverings_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Coverings"
    ADD CONSTRAINT "FK_Coverings_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("MRN") ON DELETE CASCADE;


--
-- TOC entry 2748 (class 2606 OID 24667)
-- Name: Coverings FK_Coverings_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Coverings"
    ADD CONSTRAINT "FK_Coverings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 2749 (class 2606 OID 24682)
-- Name: Medications FK_Medications_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Medications"
    ADD CONSTRAINT "FK_Medications_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("MRN") ON DELETE CASCADE;


--
-- TOC entry 2750 (class 2606 OID 24687)
-- Name: Medications FK_Medications_Patients_PatientMRN; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Medications"
    ADD CONSTRAINT "FK_Medications_Patients_PatientMRN" FOREIGN KEY ("PatientMRN") REFERENCES public."Patients"("MRN") ON DELETE RESTRICT;


--
-- TOC entry 2751 (class 2606 OID 24692)
-- Name: Medications FK_Medications_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Medications"
    ADD CONSTRAINT "FK_Medications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2752 (class 2606 OID 24707)
-- Name: Notes FK_Notes_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Notes"
    ADD CONSTRAINT "FK_Notes_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("MRN") ON DELETE CASCADE;


--
-- TOC entry 2753 (class 2606 OID 24712)
-- Name: Notes FK_Notes_Patients_PatientMRN; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Notes"
    ADD CONSTRAINT "FK_Notes_Patients_PatientMRN" FOREIGN KEY ("PatientMRN") REFERENCES public."Patients"("MRN") ON DELETE RESTRICT;


--
-- TOC entry 2754 (class 2606 OID 24717)
-- Name: Notes FK_Notes_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Notes"
    ADD CONSTRAINT "FK_Notes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2755 (class 2606 OID 24732)
-- Name: Tests FK_Tests_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Tests"
    ADD CONSTRAINT "FK_Tests_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("MRN") ON DELETE CASCADE;


--
-- TOC entry 2756 (class 2606 OID 24737)
-- Name: Tests FK_Tests_Patients_PatientMRN; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Tests"
    ADD CONSTRAINT "FK_Tests_Patients_PatientMRN" FOREIGN KEY ("PatientMRN") REFERENCES public."Patients"("MRN") ON DELETE RESTRICT;


--
-- TOC entry 2757 (class 2606 OID 24742)
-- Name: Tests FK_Tests_TypesOfTests_TestTypeId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Tests"
    ADD CONSTRAINT "FK_Tests_TypesOfTests_TestTypeId" FOREIGN KEY ("TestTypeId") REFERENCES public."TypesOfTests"("Id") ON DELETE CASCADE;


--
-- TOC entry 2758 (class 2606 OID 24747)
-- Name: Tests FK_Tests_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Tests"
    ADD CONSTRAINT "FK_Tests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE RESTRICT;


--
-- TOC entry 2746 (class 2606 OID 24773)
-- Name: Users FK_Users_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: EHRApp
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE RESTRICT;


-- Completed on 2021-03-30 20:13:51

--
-- PostgreSQL database dump complete
--

